package com.real.estate

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {

        // Default Filter For All Controllers
        defaultAllControllers(controller: '*', action: '*') {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName || controllerName == 'assets') return true
                // Access control by convention.
                accessControl()
            }
        }
    }
}
